/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as WebRouteRouteImport } from './routes/_web/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WebIndexRouteImport } from './routes/_web/index'
import { Route as AdminSubscribersRouteImport } from './routes/admin/subscribers'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminExperiencesRouteImport } from './routes/admin/experiences'
import { Route as WebContactUsRouteImport } from './routes/_web/contact-us'
import { Route as WebContactRouteImport } from './routes/_web/contact'
import { Route as AdminContactsIndexRouteImport } from './routes/admin/contacts/index'
import { Route as AdminBlogsIndexRouteImport } from './routes/admin/blogs/index'
import { Route as WebTagsIndexRouteImport } from './routes/_web/tags/index'
import { Route as WebProjectsIndexRouteImport } from './routes/_web/projects/index'
import { Route as WebBlogsIndexRouteImport } from './routes/_web/blogs/index'
import { Route as AdminBlogsNewRouteImport } from './routes/admin/blogs/new'
import { Route as WebTagsNameRouteImport } from './routes/_web/tags/$name'
import { Route as WebProjectsSlugRouteImport } from './routes/_web/projects/$slug'
import { Route as WebBlogsSlugRouteImport } from './routes/_web/blogs/$slug'
import { Route as AdminBlogsIdIndexRouteImport } from './routes/admin/blogs/$id/index'
import { Route as AdminBlogsIdEditRouteImport } from './routes/admin/blogs/$id/edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const WebRouteRoute = WebRouteRouteImport.update({
  id: '/_web',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const WebIndexRoute = WebIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebRouteRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExperiencesRoute = AdminExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => AdminRouteRoute,
} as any)
const WebContactUsRoute = WebContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => WebRouteRoute,
} as any)
const WebContactRoute = WebContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => WebRouteRoute,
} as any)
const AdminContactsIndexRoute = AdminContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogsIndexRoute = AdminBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const WebTagsIndexRoute = WebTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => WebRouteRoute,
} as any)
const WebProjectsIndexRoute = WebProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => WebRouteRoute,
} as any)
const WebBlogsIndexRoute = WebBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => WebRouteRoute,
} as any)
const AdminBlogsNewRoute = AdminBlogsNewRouteImport.update({
  id: '/blogs/new',
  path: '/blogs/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const WebTagsNameRoute = WebTagsNameRouteImport.update({
  id: '/tags/$name',
  path: '/tags/$name',
  getParentRoute: () => WebRouteRoute,
} as any)
const WebProjectsSlugRoute = WebProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => WebRouteRoute,
} as any)
const WebBlogsSlugRoute = WebBlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => WebRouteRoute,
} as any)
const AdminBlogsIdIndexRoute = AdminBlogsIdIndexRouteImport.update({
  id: '/blogs/$id/',
  path: '/blogs/$id/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogsIdEditRoute = AdminBlogsIdEditRouteImport.update({
  id: '/blogs/$id/edit',
  path: '/blogs/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WebIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/contact': typeof WebContactRoute
  '/contact-us': typeof WebContactUsRoute
  '/admin/experiences': typeof AdminExperiencesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/blogs/$slug': typeof WebBlogsSlugRoute
  '/projects/$slug': typeof WebProjectsSlugRoute
  '/tags/$name': typeof WebTagsNameRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/blogs/': typeof WebBlogsIndexRoute
  '/projects/': typeof WebProjectsIndexRoute
  '/tags/': typeof WebTagsIndexRoute
  '/admin/blogs/': typeof AdminBlogsIndexRoute
  '/admin/contacts/': typeof AdminContactsIndexRoute
  '/admin/blogs/$id/edit': typeof AdminBlogsIdEditRoute
  '/admin/blogs/$id/': typeof AdminBlogsIdIndexRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/contact': typeof WebContactRoute
  '/contact-us': typeof WebContactUsRoute
  '/admin/experiences': typeof AdminExperiencesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/': typeof WebIndexRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/blogs/$slug': typeof WebBlogsSlugRoute
  '/projects/$slug': typeof WebProjectsSlugRoute
  '/tags/$name': typeof WebTagsNameRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/blogs': typeof WebBlogsIndexRoute
  '/projects': typeof WebProjectsIndexRoute
  '/tags': typeof WebTagsIndexRoute
  '/admin/blogs': typeof AdminBlogsIndexRoute
  '/admin/contacts': typeof AdminContactsIndexRoute
  '/admin/blogs/$id/edit': typeof AdminBlogsIdEditRoute
  '/admin/blogs/$id': typeof AdminBlogsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_web': typeof WebRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_web/contact': typeof WebContactRoute
  '/_web/contact-us': typeof WebContactUsRoute
  '/admin/experiences': typeof AdminExperiencesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/_web/': typeof WebIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_web/blogs/$slug': typeof WebBlogsSlugRoute
  '/_web/projects/$slug': typeof WebProjectsSlugRoute
  '/_web/tags/$name': typeof WebTagsNameRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/_web/blogs/': typeof WebBlogsIndexRoute
  '/_web/projects/': typeof WebProjectsIndexRoute
  '/_web/tags/': typeof WebTagsIndexRoute
  '/admin/blogs/': typeof AdminBlogsIndexRoute
  '/admin/contacts/': typeof AdminContactsIndexRoute
  '/admin/blogs/$id/edit': typeof AdminBlogsIdEditRoute
  '/admin/blogs/$id/': typeof AdminBlogsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/contact'
    | '/contact-us'
    | '/admin/experiences'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/subscribers'
    | '/admin/'
    | '/auth/'
    | '/blogs/$slug'
    | '/projects/$slug'
    | '/tags/$name'
    | '/admin/blogs/new'
    | '/blogs/'
    | '/projects/'
    | '/tags/'
    | '/admin/blogs/'
    | '/admin/contacts/'
    | '/admin/blogs/$id/edit'
    | '/admin/blogs/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/contact'
    | '/contact-us'
    | '/admin/experiences'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/subscribers'
    | '/'
    | '/admin'
    | '/auth'
    | '/blogs/$slug'
    | '/projects/$slug'
    | '/tags/$name'
    | '/admin/blogs/new'
    | '/blogs'
    | '/projects'
    | '/tags'
    | '/admin/blogs'
    | '/admin/contacts'
    | '/admin/blogs/$id/edit'
    | '/admin/blogs/$id'
  id:
    | '__root__'
    | '/_web'
    | '/admin'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/_web/contact'
    | '/_web/contact-us'
    | '/admin/experiences'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/subscribers'
    | '/_web/'
    | '/admin/'
    | '/auth/'
    | '/_web/blogs/$slug'
    | '/_web/projects/$slug'
    | '/_web/tags/$name'
    | '/admin/blogs/new'
    | '/_web/blogs/'
    | '/_web/projects/'
    | '/_web/tags/'
    | '/admin/blogs/'
    | '/admin/contacts/'
    | '/admin/blogs/$id/edit'
    | '/admin/blogs/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WebRouteRoute: typeof WebRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_web': {
      id: '/_web'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WebRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_web/': {
      id: '/_web/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WebIndexRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/experiences': {
      id: '/admin/experiences'
      path: '/experiences'
      fullPath: '/admin/experiences'
      preLoaderRoute: typeof AdminExperiencesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_web/contact-us': {
      id: '/_web/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof WebContactUsRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_web/contact': {
      id: '/_web/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof WebContactRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/admin/contacts/': {
      id: '/admin/contacts/'
      path: '/contacts'
      fullPath: '/admin/contacts/'
      preLoaderRoute: typeof AdminContactsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blogs/': {
      id: '/admin/blogs/'
      path: '/blogs'
      fullPath: '/admin/blogs/'
      preLoaderRoute: typeof AdminBlogsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_web/tags/': {
      id: '/_web/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof WebTagsIndexRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_web/projects/': {
      id: '/_web/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof WebProjectsIndexRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_web/blogs/': {
      id: '/_web/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof WebBlogsIndexRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/admin/blogs/new': {
      id: '/admin/blogs/new'
      path: '/blogs/new'
      fullPath: '/admin/blogs/new'
      preLoaderRoute: typeof AdminBlogsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_web/tags/$name': {
      id: '/_web/tags/$name'
      path: '/tags/$name'
      fullPath: '/tags/$name'
      preLoaderRoute: typeof WebTagsNameRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_web/projects/$slug': {
      id: '/_web/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof WebProjectsSlugRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_web/blogs/$slug': {
      id: '/_web/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof WebBlogsSlugRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/admin/blogs/$id/': {
      id: '/admin/blogs/$id/'
      path: '/blogs/$id'
      fullPath: '/admin/blogs/$id/'
      preLoaderRoute: typeof AdminBlogsIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blogs/$id/edit': {
      id: '/admin/blogs/$id/edit'
      path: '/blogs/$id/edit'
      fullPath: '/admin/blogs/$id/edit'
      preLoaderRoute: typeof AdminBlogsIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface WebRouteRouteChildren {
  WebContactRoute: typeof WebContactRoute
  WebContactUsRoute: typeof WebContactUsRoute
  WebIndexRoute: typeof WebIndexRoute
  WebBlogsSlugRoute: typeof WebBlogsSlugRoute
  WebProjectsSlugRoute: typeof WebProjectsSlugRoute
  WebTagsNameRoute: typeof WebTagsNameRoute
  WebBlogsIndexRoute: typeof WebBlogsIndexRoute
  WebProjectsIndexRoute: typeof WebProjectsIndexRoute
  WebTagsIndexRoute: typeof WebTagsIndexRoute
}

const WebRouteRouteChildren: WebRouteRouteChildren = {
  WebContactRoute: WebContactRoute,
  WebContactUsRoute: WebContactUsRoute,
  WebIndexRoute: WebIndexRoute,
  WebBlogsSlugRoute: WebBlogsSlugRoute,
  WebProjectsSlugRoute: WebProjectsSlugRoute,
  WebTagsNameRoute: WebTagsNameRoute,
  WebBlogsIndexRoute: WebBlogsIndexRoute,
  WebProjectsIndexRoute: WebProjectsIndexRoute,
  WebTagsIndexRoute: WebTagsIndexRoute,
}

const WebRouteRouteWithChildren = WebRouteRoute._addFileChildren(
  WebRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminExperiencesRoute: typeof AdminExperiencesRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogsNewRoute: typeof AdminBlogsNewRoute
  AdminBlogsIndexRoute: typeof AdminBlogsIndexRoute
  AdminContactsIndexRoute: typeof AdminContactsIndexRoute
  AdminBlogsIdEditRoute: typeof AdminBlogsIdEditRoute
  AdminBlogsIdIndexRoute: typeof AdminBlogsIdIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminExperiencesRoute: AdminExperiencesRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogsNewRoute: AdminBlogsNewRoute,
  AdminBlogsIndexRoute: AdminBlogsIndexRoute,
  AdminContactsIndexRoute: AdminContactsIndexRoute,
  AdminBlogsIdEditRoute: AdminBlogsIdEditRoute,
  AdminBlogsIdIndexRoute: AdminBlogsIdIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WebRouteRoute: WebRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
