/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EditorTestRouteImport } from './routes/editor-test'
import { Route as WebRouteRouteImport } from './routes/_web/route'
import { Route as WebIndexRouteImport } from './routes/_web/index'
import { Route as WebContactUsRouteImport } from './routes/_web/contact-us'

const EditorTestRoute = EditorTestRouteImport.update({
  id: '/editor-test',
  path: '/editor-test',
  getParentRoute: () => rootRouteImport,
} as any)
const WebRouteRoute = WebRouteRouteImport.update({
  id: '/_web',
  getParentRoute: () => rootRouteImport,
} as any)
const WebIndexRoute = WebIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebRouteRoute,
} as any)
const WebContactUsRoute = WebContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => WebRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/editor-test': typeof EditorTestRoute
  '/contact-us': typeof WebContactUsRoute
  '/': typeof WebIndexRoute
}
export interface FileRoutesByTo {
  '/editor-test': typeof EditorTestRoute
  '/contact-us': typeof WebContactUsRoute
  '/': typeof WebIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_web': typeof WebRouteRouteWithChildren
  '/editor-test': typeof EditorTestRoute
  '/_web/contact-us': typeof WebContactUsRoute
  '/_web/': typeof WebIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/editor-test' | '/contact-us' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/editor-test' | '/contact-us' | '/'
  id: '__root__' | '/_web' | '/editor-test' | '/_web/contact-us' | '/_web/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WebRouteRoute: typeof WebRouteRouteWithChildren
  EditorTestRoute: typeof EditorTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/editor-test': {
      id: '/editor-test'
      path: '/editor-test'
      fullPath: '/editor-test'
      preLoaderRoute: typeof EditorTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_web': {
      id: '/_web'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WebRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_web/': {
      id: '/_web/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WebIndexRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_web/contact-us': {
      id: '/_web/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof WebContactUsRouteImport
      parentRoute: typeof WebRouteRoute
    }
  }
}

interface WebRouteRouteChildren {
  WebContactUsRoute: typeof WebContactUsRoute
  WebIndexRoute: typeof WebIndexRoute
}

const WebRouteRouteChildren: WebRouteRouteChildren = {
  WebContactUsRoute: WebContactUsRoute,
  WebIndexRoute: WebIndexRoute,
}

const WebRouteRouteWithChildren = WebRouteRoute._addFileChildren(
  WebRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WebRouteRoute: WebRouteRouteWithChildren,
  EditorTestRoute: EditorTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
